# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Exclude:
    - 'lib/math_ml/util.rb'

# Offense count: 1
# Configuration parameters: IgnoreLiteralBranches, IgnoreConstantBranches.
Lint/DuplicateBranch:
  Exclude:
    - 'lib/math_ml/latex.rb'

# Offense count: 2
# Configuration parameters: AllowComments, AllowEmptyLambdas.
Lint/EmptyBlock:
  Exclude:
    - 'spec/math_ml/util_spec.rb'

# Offense count: 2
# Configuration parameters: AllowComments.
Lint/EmptyConditionalBody:
  Exclude:
    - 'symbols/fetch_symbol.rb'

# Offense count: 4
# Configuration parameters: AllowComments.
Lint/EmptyWhen:
  Exclude:
    - 'lib/math_ml/latex.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 1
Lint/RescueException:
  Exclude:
    - 'spec/spec_util.rb'

# Offense count: 1
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'spec/math_ml/util_spec.rb'

# Offense count: 18
Lint/UselessAssignment:
  Exclude:
    - 'lib/math_ml/latex.rb'
    - 'lib/math_ml/util.rb'
    - 'spec/math_ml/util_spec.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 45
# Configuration parameters: CheckForMethodsWithNoSideEffects.
Lint/Void:
  Exclude:
    - 'symbols/fetch_symbol_spec.rb'

# Offense count: 36
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 88

# Offense count: 22
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 542

# Offense count: 6
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 4

# Offense count: 3
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 319

# Offense count: 28
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 24

# Offense count: 47
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 65

# Offense count: 7
# Configuration parameters: CountComments, CountAsOne.
Metrics/ModuleLength:
  Max: 2094

# Offense count: 1
# Configuration parameters: CountKeywordArgs, MaxOptionalParameters.
Metrics/ParameterLists:
  Max: 10

# Offense count: 25
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 26

# Offense count: 3
Naming/AccessorMethodName:
  Exclude:
    - 'lib/math_ml/util.rb'

# Offense count: 3
Naming/ConstantName:
  Exclude:
    - 'lib/math_ml/symbol/character_reference.rb'
    - 'lib/math_ml/symbol/entity_reference.rb'
    - 'lib/math_ml/symbol/utf8.rb'

# Offense count: 16
# Configuration parameters: ForbiddenDelimiters.
# ForbiddenDelimiters: (?-mix:(^|\s)(EO[A-Z]{1}|END)(\s|$))
Naming/HeredocDelimiterNaming:
  Exclude:
    - 'lib/math_ml/latex.rb'
    - 'sample/fonts.rb'
    - 'spec/math_ml/latex/macro_spec.rb'
    - 'spec/math_ml/latex/parser_spec.rb'
    - 'spec/math_ml/string_spec.rb'
    - 'spec/math_ml/util_spec.rb'
    - 'symbols/fetch_symbol.rb'
    - 'symbols/fetch_symbol_spec.rb'

# Offense count: 3
# Configuration parameters: EnforcedStyle, AllowedPatterns, IgnoredPatterns.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Exclude:
    - 'lib/math_ml/util.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 42
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: at, by, db, id, in, io, ip, of, on, os, pp, to
Naming/MethodParameterName:
  Exclude:
    - 'lib/math_ml.rb'
    - 'lib/math_ml/element.rb'
    - 'lib/math_ml/latex.rb'
    - 'lib/math_ml/util.rb'
    - 'spec/math_ml/util_spec.rb'
    - 'symbols/fetch_symbol.rb'
    - 'symbols/fetch_symbol_spec.rb'

# Offense count: 2
RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/**/*.rb'
    - 'spec/math_ml/latex/macro_spec.rb'
    - 'symbols/fetch_symbol_spec.rb'

# Offense count: 1
# Configuration parameters: Prefixes.
# Prefixes: when, with, without
RSpec/ContextWording:
  Exclude:
    - 'spec/math_ml/latex/parser_spec.rb'

# Offense count: 1
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
    - '**/spec/routing/**/*'
    - '**/spec/system/**/*'
    - '**/spec/views/**/*'
    - 'symbols/fetch_symbol_spec.rb'

# Offense count: 74
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: SkipBlocks, EnforcedStyle.
# SupportedStyles: described_class, explicit
RSpec/DescribedClass:
  Exclude:
    - 'spec/math_ml/element_spec.rb'
    - 'spec/math_ml/latex/macro_spec.rb'
    - 'spec/math_ml/latex/parser_spec.rb'
    - 'spec/math_ml/string_spec.rb'
    - 'spec/math_ml/util_spec.rb'
    - 'spec/math_ml_spec.rb'

# Offense count: 66
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 58

# Offense count: 1
# This cop supports safe auto-correction (--auto-correct).
RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**/*'
    - 'spec/math_ml/latex/scanner_spec.rb'

# Offense count: 3
# Configuration parameters: Include, CustomTransform, IgnoreMethods, SpecSuffixOnly.
# Include: **/*_spec*rb*, **/spec/**/*
RSpec/FilePath:
  Exclude:
    - 'spec/math_ml/latex/macro_spec.rb'
    - 'spec/math_ml/latex/parser_spec.rb'
    - 'spec/math_ml/latex/scanner_spec.rb'

# Offense count: 1
RSpec/IdenticalEqualityAssertion:
  Exclude:
    - 'spec/math_ml/latex/scanner_spec.rb'

# Offense count: 58
# Configuration parameters: AssignmentOnly.
RSpec/InstanceVariable:
  Exclude:
    - 'spec/math_ml/latex/macro_spec.rb'
    - 'spec/math_ml/latex/parser_spec.rb'
    - 'symbols/fetch_symbol_spec.rb'

# Offense count: 3
RSpec/MultipleDescribes:
  Exclude:
    - 'spec/math_ml/string_spec.rb'
    - 'spec/math_ml/util_spec.rb'
    - 'symbols/fetch_symbol_spec.rb'

# Offense count: 80
RSpec/MultipleExpectations:
  Max: 25

# Offense count: 3
RSpec/NestedGroups:
  Max: 4

# Offense count: 1
# This cop supports safe auto-correction (--auto-correct).
Rake/Desc:
  Exclude:
    - 'Rakefile'

# Offense count: 7
# This cop supports unsafe auto-correction (--auto-correct-all).
Security/IoMethods:
  Exclude:
    - 'symbols/fetch_symbol.rb'
    - 'symbols/fetch_symbol_spec.rb'
    - 'symbols/w3c/converter.rb'

# Offense count: 4
Security/Open:
  Exclude:
    - 'symbols/w3c/converter.rb'

# Offense count: 3
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/math_ml/latex/builtin.rb'
    - 'lib/math_ml/latex/builtin/symbol.rb'
    - 'lib/math_ml/util.rb'

# Offense count: 5
Style/ClassVars:
  Exclude:
    - 'lib/math_ml/string.rb'
    - 'lib/math_ml/util.rb'

# Offense count: 1
Style/CombinableLoops:
  Exclude:
    - 'symbols/fetch_symbol.rb'

# Offense count: 1
# This cop supports safe auto-correction (--auto-correct).
Style/CommentedKeyword:
  Exclude:
    - 'spec/math_ml/util_spec.rb'

# Offense count: 50
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/math_ml.rb'
    - 'lib/math_ml/element.rb'
    - 'lib/math_ml/latex.rb'
    - 'lib/math_ml/latex/builtin.rb'
    - 'lib/math_ml/string.rb'
    - 'lib/math_ml/symbol/character_reference.rb'
    - 'lib/math_ml/symbol/entity_reference.rb'
    - 'lib/math_ml/symbol/utf8.rb'
    - 'lib/math_ml/util.rb'
    - 'symbols/w3c/converter.rb'

# Offense count: 26
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 5
# Configuration parameters: MinBodyLength, AllowConsecutiveConditionals.
Style/GuardClause:
  Exclude:
    - 'lib/math_ml/latex.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 1
# This cop supports unsafe auto-correction (--auto-correct-all).
# Configuration parameters: AllowedReceivers.
Style/HashEachMethods:
  Exclude:
    - 'symbols/w3c/converter.rb'

# Offense count: 2
# This cop supports safe auto-correction (--auto-correct).
Style/IdenticalConditionalBranches:
  Exclude:
    - 'symbols/fetch_symbol.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'symbols/fetch_symbol.rb'

# Offense count: 40
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'Rakefile'
    - 'lib/math_ml/element.rb'
    - 'lib/math_ml/latex.rb'
    - 'lib/math_ml/latex/builtin/symbol.rb'
    - 'lib/math_ml/symbol/character_reference.rb'
    - 'lib/math_ml/symbol/entity_reference.rb'
    - 'lib/math_ml/symbol/utf8.rb'
    - 'lib/math_ml/util.rb'
    - 'sample/fonts.rb'
    - 'symbols/fetch_symbol.rb'
    - 'symbols/w3c/converter.rb'

# Offense count: 12
# This cop supports unsafe auto-correction (--auto-correct-all).
# Configuration parameters: EnforcedStyle, IgnoredMethods.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'lib/math_ml/element.rb'
    - 'lib/math_ml/latex.rb'
    - 'lib/math_ml/util.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 14
# Configuration parameters: AllowedMethods.
# AllowedMethods: respond_to_missing?
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/math_ml.rb'
    - 'lib/math_ml/latex.rb'
    - 'lib/math_ml/string.rb'
    - 'lib/math_ml/util.rb'
    - 'spec/spec_util.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 24
# This cop supports safe auto-correction (--auto-correct).
Style/PerlBackrefs:
  Exclude:
    - 'lib/math_ml/latex.rb'
    - 'lib/math_ml/util.rb'
    - 'spec/math_ml/util_spec.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 6
# This cop supports unsafe auto-correction (--auto-correct-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: short, verbose
Style/PreferredHashMethods:
  Exclude:
    - 'lib/math_ml/latex.rb'

# Offense count: 1
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: ConvertCodeThatCanStartToReturnNil, AllowedMethods, MaxChainLength.
# AllowedMethods: present?, blank?, presence, try, try!
Style/SafeNavigation:
  Exclude:
    - 'symbols/fetch_symbol.rb'

# Offense count: 11
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: RequireEnglish, EnforcedStyle.
# SupportedStyles: use_perl_names, use_english_names, use_builtin_english_names
Style/SpecialGlobalVars:
  Exclude:
    - 'bin/bundle'
    - 'sample/fonts.rb'
    - 'spec/spec_util.rb'
    - 'symbols/fetch_symbol.rb'
    - 'symbols/w3c/converter.rb'

# Offense count: 7
# This cop supports unsafe auto-correction (--auto-correct-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'lib/math_ml/element.rb'
    - 'lib/math_ml/latex.rb'
    - 'spec/math_ml/util_spec.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 1
# This cop supports unsafe auto-correction (--auto-correct-all).
# Configuration parameters: AllowMethodsWithArguments, IgnoredMethods, AllowComments.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'symbols/w3c/converter.rb'

# Offense count: 8
# This cop supports unsafe auto-correction (--auto-correct-all).
Style/ZeroLengthPredicate:
  Exclude:
    - 'lib/math_ml/element.rb'
    - 'lib/math_ml/latex.rb'
    - 'lib/math_ml/util.rb'
    - 'symbols/fetch_symbol.rb'

# Offense count: 101
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 359
